In [1]:
import pandas as pd
import xarray as xr

df_price = pd.read_parquet('../temp/df_price.parquet')
data = xr.open_dataarray('../temp/data_share_holdings.nc')

sell = - data.diff(dim = 'date').clip(max = 0)
buy = data.diff(dim = 'date').clip(min = 0)




In [ ]:
df_price_1 = df_price.iloc[:, -sell.shape[0]:].transpose()
price = df_price_1.values.reshape(df_price_1.shape + (1,))
sell_price = sell * price
buy_price = buy * price
cash = (sell_price - buy_price).sum(dim = ['symbol', 'account'])
print(sell_price.sum(dim = ['symbol', 'account']))
print(buy_price.sum(dim = ['symbol', 'account']))


<xarray.DataArray (date: 13)> Size: 104B
array([142962.8429, 172369.3506, 107949.5771, 104664.081 , 140697.8936,
       130354.4682,  69742.0138, 127445.7158, 130954.264 , 100785.967 ,
       119601.5333, 151923.02  , 160866.7678])
Coordinates:
  * date     (date) datetime64[ns] 104B 2025-09-08 2025-10-06 ... 2026-08-10
<xarray.DataArray (date: 13)> Size: 104B
array([142758.8087, 173358.2255, 110576.6546, 107826.8716, 144864.9547,
       135021.9598,  75854.4675, 134092.7691, 138680.4289, 109788.0738,
       129577.2629, 161838.9309, 171241.54  ])
Coordinates:
  * date     (date) datetime64[ns] 104B 2025-09-08 2025-10-06 ... 2026-08-10


: 

In [14]:
df_price_1.values.reshape(df_price_1.shape + (1,))



array([[[6.9859700e+01],
        [6.0915600e+01],
        [1.0979160e+02],
        [1.3281060e+02],
        [5.4704000e+02],
        [1.6914790e+02],
        [4.2428799e+03],
        [2.2130010e+02],
        [4.9378000e+02],
        [1.5802200e+01],
        [2.1447000e+00],
        [1.6654410e+02],
        [5.1969050e+02],
        [9.6621260e+02],
        [2.6043900e+01],
        [1.4945480e+02],
        [9.3240000e+01],
        [5.0930000e-01],
        [2.5169700e+01],
        [1.1717000e+02],
        [2.3117300e+01],
        [1.6142550e+02],
        [3.7690000e+01],
        [1.3478930e+02],
        [1.5382000e+03],
        [4.5283400e+01],
        [5.0445000e+01],
        [1.1293790e+02],
        [1.9281800e+01],
        [1.3795350e+02],
        [9.0512500e+01],
        [2.5605200e+01],
        [7.3506250e+02],
        [4.5031380e+02],
        [6.9498460e+02],
        [2.3469600e+03],
        [7.4984240e+02],
        [1.7870130e+02],
        [8.5831410e+02],
        [4.9506460e+02],
